### ISSUE TITLE
Error in comment, T should be time and not a repetition of temperature

### ISSUE THREAD

**Issue by jamadagni** [nourani/ScientificQuantities#15]
https://github.com/nourani/ScientificQuantities/blob/0e7bd93bbf8e11514b3a1cacac1f8101e0c50549/include/ScientificQuantities.hpp#L58-L59

I think third base quantity should be Time and not Temperature because “Thermodynamic Temperature” is there later on as TT.

**Comment by nourani** [comment]
Thanks @jamadagni. This is fortunately just a typo in the documentation. Will fix
